import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, PT_Mono, Palette_Mosaic} from "next/font/google";
import Link  from 'next/link'
import "./globals.css";

const pallete_mosaic = Palette_Mosaic({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




// function NavBar(){
//   return(
//     <div className="flex flex-row justify-center items-center">
//         <Link 
//           href = {"/button_demo"}
//         >
//           Button Demo
//         </Link>

//          <Link 
//             href = {"/card_demo"}
//           >
//           Card Demo
//         </Link>
//     </div>
//   )
// }


function NavBar(){
  return(
    <div className="flex flex-row justify-center items-center gap-16">
      <Link
        href={'/button_demo'}
        className="hover:text-red-500"
      >
        Button Demo
      </Link>

      <Link
        href={'/card_demo'}
        className="hover:text-red-500"
      >
        Card Demo
      </Link>
    </div>
  )
}




export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${pallete_mosaic.className} h-full antialiased `}
    >
      <NavBar />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
